# Insect Default Configuration

# General settings
[general]
max_depth = 10
include_hidden = false

# Analyzer settings
[analyzers]
static = true
config = true
binary = true
metadata = true
secrets = true
browser_theft = true
crypto_wallet = true

# File pattern settings
[patterns]
include = ["*"]
exclude = [
    "*.git/*",
    "node_modules/*",
    "venv/*",
    ".venv/*",
    "*.pyc",
    "__pycache__/*",
    "*.min.js",
    "*.min.css",
]

# Severity settings
[severity]
min_level = "low"  # Options: low, medium, high, critical

# Sensitivity settings for metadata analysis
[sensitivity]
level = "normal"  # Options: low, normal, high, very_high
# low: Only obvious security issues
# normal: Standard security checks (default)
# high: Include more speculative findings
# very_high: Include all potential security-related patterns

# Allowlist settings
[allowlist]
files = []
directories = []
patterns = []
findings = []  # List of finding IDs to ignore

# Cache settings
[cache]
enabled = true  # Enable or disable the scan cache
cleanup_enabled = true  # Enable or disable automatic cleanup of old cache entries
max_age_days = 30  # Maximum age of cache entries in days

# Progress bar settings
[progress]
enabled = true  # Enable or disable the progress bar

# Browser theft detection settings
[browser_theft]
enable_browser_history_detection = true
enable_browser_storage_detection = true
enable_credential_detection = true
enable_extension_detection = true

# Cryptocurrency wallet theft detection settings
[crypto_wallet]
enable_wallet_file_detection = true
enable_private_key_detection = true
enable_seed_phrase_detection = true
enable_crypto_api_detection = true
enable_address_enumeration_detection = true
